### ISSUE TITLE
Simple model not fitting with full STERGM

### ISSUE THREAD

**Issue by smjenness** [statnet/tergm#14] opened 2020-07-23 12:59 UTC
This simple model fits fine with the Carnegie dissolution approximation does not fit with a full STERGM. Testing against the Github masters for Statnet.

```r
num.g1 <- num.g2 <- 250
nw <- network.initialize(n = num.g1 + num.g2, directed = FALSE)
group <- rep(1:2, times = c(num.g1, num.g2))
nw <- set.vertex.attribute(nw, attrname = "group", value = group)
fit <- stergm(nw,
              formation = ~edges + degree(0:1, by = "group") + nodematch("group"),
              dissolution = ~offset(edges),
              targets = "formation",
              target.stats = c(165, 100, 137.5, 135, 77.5, 0),
              offset.coef.form = NULL,
              offset.coef.diss = log(9),
              estimate = "EGMME",
              eval.loglik = FALSE)
```

With the output error:

```r
Observed statistic(s) nodematch.group are at their smallest attainable values. Their coefficients will be fixed at -Inf.
Unable to match target stats. Using MCMLE estimation.
Starting maximum pseudolikelihood estimation (MPLE):
Evaluating the predictor and response matrix.
Maximizing the pseudolikelihood.
Finished MPLE.
Starting Monte Carlo maximum likelihood estimation (MCMLE):
Iteration 1 of at most 20:
Optimizing with step length 1.
The log-likelihood improved by 0.2147.
Step length converged once. Increasing MCMC sample size.
Iteration 2 of at most 20:
Optimizing with step length 1.
The log-likelihood improved by 0.008556.
Step length converged twice. Stopping.
Finished MCMLE.
This model was fit using MCMC.  To examine model diagnostics and check for degeneracy, use the
mcmc.diagnostics() function.
========  Phase 1: Burn in, get initial gradient values, and find a configuration under which all targets vary. ========
Burning in... Done.
Attempt 1 :
Something went very wrong. Restarting with smaller gain.
========  Phase 1: Burn in, get initial gradient values, and find a configuration under which all targets vary. ========
Burning in... Done.
Attempt 1 :
Something went very wrong. Restarting with smaller gain.
========  Phase 1: Burn in, get initial gradient values, and find a configuration under which all targets vary. ========
Burning in... Done.
Attempt 1 :
Something went very wrong. Restarting with smaller gain.
========  Phase 1: Burn in, get initial gradient values, and find a configuration under which all targets vary. ========
Burning in... Done.
Attempt 1 :
Something went very wrong. Restarting with smaller gain.
========  Phase 1: Burn in, get initial gradient values, and find a configuration under which all targets vary. ========
Burning in... Done.
Attempt 1 :
Something went very wrong. Restarting with smaller gain.
========  Phase 1: Burn in, get initial gradient values, and find a configuration under which all targets vary. ========
Burning in... Done.
Attempt 1 :
Something went very wrong. Restarting with smaller gain.
========  Phase 1: Burn in, get initial gradient values, and find a configuration under which all targets vary. ========
Burning in... Done.
Attempt 1 :
Something went very wrong. Restarting with smaller gain.
========  Phase 1: Burn in, get initial gradient values, and find a configuration under which all targets vary. ========
Burning in... Done.
Attempt 1 :
Something went very wrong. Restarting with smaller gain.
========  Phase 1: Burn in, get initial gradient values, and find a configuration under which all targets vary. ========
Burning in... Done.
Attempt 1 :
Something went very wrong. Restarting with smaller gain.
========  Phase 1: Burn in, get initial gradient values, and find a configuration under which all targets vary. ========
Burning in... Done.
Attempt 1 :
Something went very wrong. Restarting with smaller gain.
Error in stergm.EGMME.SA(theta.form0, theta.diss0, nw, model.form, model.diss,  : 
  object 'V.par' not found
```

**Comment by chad-klumb** [comment] 2020-07-23 15:48
With CRAN packages I get a fit using

```
require(tergm)
num.g1 <- num.g2 <- 250
nw <- network.initialize(n = num.g1 + num.g2, directed = FALSE)
group <- rep(1:2, times = c(num.g1, num.g2))
nw <- set.vertex.attribute(nw, attrname = "group", value = group)
fit <- stergm(nw,
              formation = ~edges + degree(0:1, by = "group") + offset(nodematch("group")),
              dissolution = ~offset(edges),
              targets = "formation",
              target.stats = c(165, 100, 137.5, 135, 77.5),
              offset.coef.form = -Inf,
              offset.coef.diss = log(9),
              estimate = "EGMME",
              eval.loglik = FALSE)
```

With `master` some updates to offset handling will be required to get things to work.  (I should be able to make those updates soon.)

Is this for NME?  Are you planning to use CRAN versions?

It's possible there may be a general issue with using 0 (or, more generally, extremal) target stats in `EGMME` since the first step of the algorithm is

```
========  Phase 1: Burn in, get initial gradient values, and find a configuration under which all targets vary. ========
```

The last point ("under which all targets vary") may be at odds with keeping some targets = to 0 (or some other extreme value).

**Comment by martinamorris** [comment] 2020-07-23 16:04
@chad-klumb is this possibly the same issue I ran into re: SAN?

@smjenness i also had trouble with a simple target stats based ergm.  fixed by setting `init.MPLE.samplesize`

```
  set.control.ergm = control.ergm(
                       MCMC.interval = 2e4,
                       init.MPLE.samplesize = 1e6)
```
see: https://github.com/statnet/ergm/issues/153

**Comment by chad-klumb** [comment] 2020-07-23 17:47
With statnet/ergm@8a89091487bc9ba77b6c35388430b02ba6b3c4f8 the `stergm` call I posted above should run with `master` branches.

A feature in `tergm` `dev` but not currently in `master` is the ability to use offsets in the `targets` formula; these are only taken into account during the initial `SAN` run in the `tergm.EGMME` function (not during the `EGMME` algorithm itself), and you need to pass `SAN.offsets` as an additional argument to `tergm`.  In `master` with the present model, it appears that even without the offset in the `SAN` run, the `EGMME` clears any illicit edges during its initial 1000 time step burnin, so this is probably a non-issue for the present case.  (But, if people are using `master`, and if we're pushing `master` to CRAN before `dev`, we may want to add this functionality to `master` anyway).  In `master`, the `stergm.EGMME.initialfit` function, which uses `ergm` and the `formation` formula, does take the offset into account already.

As a general matter I don't think it's a bad idea to increase `init.MPLE.samplesize`.  Since this argument is somewhat obscure, and the symptoms of it being too low do not always make it clear what the problem is, I think the best option there would be to increase the default value in `ergm`, so that most users don't need to worry about it most of the time.

**Closed** 2020-08-06 23:55 UTC
